OPENAI_API_KEY="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"
PINECONE_ENV="gcp-starter"
PINECONE_API_KEY="46d72819-8c78-4d98-b5c3-0f3320dcc4ca"
PROMPTLAYER="pl_bd3c669ffb9f07b511c2ea54feb2f333"
